name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration=Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        API_KEY: ${{ secrets.API_KEY }}
    - name: Pack NuGet package
      run: dotnet pack --configuration=Release --no-build --output=./output
    - name: Upload NuGet package as release asset
      uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./output/*.nupkg
          asset_name: mypackage.nupkg
          asset_content_type: application/zip

